[build.environment]
  NPM_FLAGS = "--version"

[build]
  command = "npm run build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

  [[redirects]]
    from = "/:lang/*"
    to = "/:lang/404/"
    status = 404
